### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by d47081** [chesslablab/website#123]
Hi there! 

Good work, already have updated to this implementation!

So what about multi-language interface? As client based on Symfony, I can advice [Crowdin](https://crowdin.com) adaptor, here is documentation:
https://symfony.com/doc/current/translation.html
https://store.crowdin.com/symfony

Also, here is small wiki tutorial for another project could help you with API:
https://github.com/YGGverse/YGGtracker/wiki/Translations

I'm ready to participate Ukrainian translations!
Also released few local announces about Chesslablab project

**Comment by programarivm** [comment]
It seems as if this issue can be elaborated in more detail.

What about implementing a basic setup using the `symfony/translation` component as per the docs at [Translations](https://symfony.com/doc/current/translation.html)? 

Something like the following will be a good starting point.

```php
use Symfony\Contracts\Translation\TranslatorInterface;

public function index(TranslatorInterface $translator): Response
{
    $translated = $translator->trans('Enter Invite Code');

    // ...
}
```

Keep it up,

**Comment by programarivm** [comment]
See https://github.com/chesslablab/website/issues/190
