### ISSUE TITLE
Announcement on alternative.to

### ISSUE THREAD

**Issue by d47081** [chesslablab/website#125]
I'm using this website to search alternatives and suppose it would be useful to promote Chesslablab project there

**Comment by programarivm** [comment]
Well at the moment the database is still quite small containing sample data but hopefully the repos can be used and extended by developers to create amazing chess web apps. 

I can't wait to see what you come up with!

**Comment by programarivm** [comment]
AlternativeTo is definitely an excellent site to find apps. I was thinking along the lines of letting chesslablab.org grow organically for a while. It'd be amazing if the database could be updated with more games for example. This would encourage users to use it for learning purposes. The thing is the servers being used to host the app have a maintenance cost.
