### ISSUE TITLE
Modal popup design for Training > Endgame Skills

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#19]
A modal popup needs to open by clicking on **Training > Endgame Skills** similar to the SPA version.

![figure_01](https://github.com/chesslablab/mpablab/assets/4062000/2fcebfbd-a62b-42cd-9014-cdf5f055d921)
**Figure 1**. Click on **Training > Endgame Skills**.

![figure_02](https://github.com/chesslablab/mpablab/assets/4062000/6ea80e41-b8b6-4437-83bb-73c569c27171)
**Figure 2**. Click on the **Endgame** field.

This modal is to be implemented using [Bootstrap's JavaScript modal](https://getbootstrap.com/docs/5.0/components/modal/) plugin. No additional programming is required to close this issue — just display the modal popup, it's a really good first issue to get familiar with the codebase!

Keep it up, and happy coding.

**Comment by replyre** [comment]
hello :) is this issue still open ?

**Comment by programarivm** [comment]
@replyre, welcome to ChesslabLab.

Thank you for joining the community.

Please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

I can't wait to see what you come up with!

**Comment by replyre** [comment]
Sure!

**Comment by programarivm** [comment]
👋 Hey @replyre, how are things going? Could you set up the website on your localhost?

**Comment by replyre** [comment]
hello @programarivm, I downloaded and set everything up and launched the localhost using the php server command : 

> php -S localhost:8000 -t public  

but I getting a websocket error : 

![image](https://github.com/chesslablab/website/assets/121796450/2f92d9e3-522d-4bc2-bf69-46b60dac7618)

would appreciate any help.

**Comment by programarivm** [comment]
Well, if I had to guess, I would say that the chess server probably is not up and running because the SSL certificate has not been installed yet.

```text
php cli/workerman/wss.php start
Welcome to PHP Chess Server
Commands available:
/accept {"jwt":"<string>"} Accepts an invitation to play online with an opponent.
/draw {"action":["accept","decline","propose"]} Allows to offer a draw.
/heuristics {"fen":"<string>","variant":"<string>"} Returns the heuristics of a chess position.
/leave {"action":["accept"]} Allows to leave a game.
/legal {"position":"<string>"} Returns the legal FEN positions of a piece.
/online_games Returns the online games waiting to be accepted.
/play_lan {"color":"<string>","lan":"<string>"} Plays a chess move in long algebraic notation.
/randomizer {"turn":"<string>","items":"<string>"} Starts a random position.
/rematch {"action":["accept","decline","propose"]} Allows to offer a rematch.
/resign {"action":["accept"]} Allows to resign a game.
/restart {"hash":"<string>"} Restarts a game.
/start {"variant":["960","capablanca","capablanca-fischer","classical"],"mode":["fen","san","play","stockfish"],"settings":{"color":["w","b"],"fen":"<string>","movetext":"<string>","settings":"<string>","startPos":"<string>"}} Starts a new game.
/stockfish {"options":{"Skill Level":"int"},"params":{"depth":"int"}} Returns Stockfish's response to the current position.
/takeback {"action":["accept","decline","propose"]} Allows to takeback a move.
/tutor_fen {"fen":"<string>","variant":"<string>"} Explains a FEN position in terms of chess concepts.
/undo Undoes the last move.

Listening to commands...
Workerman[cli/workerman/wss.php] start in DEBUG mode
-------------------------------------------------------------- WORKERMAN --------------------------------------------------------------
Workerman version:4.1.15          PHP version:8.3.2-1+0~20240120.16+debian11~1.gbpb43448           Event-Loop:\Workerman\Events\Select
--------------------------------------------------------------- WORKERS ---------------------------------------------------------------
proto   user            worker          listen                      processes    status           
ssl     standard        none            websocket://0.0.0.0:8443    1             [OK]            
---------------------------------------------------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.

```
May I ask how the certificate has been installed on your localhost? 

See https://github.com/chesslablab/website/issues/20

Keep it up,
