### ISSUE TITLE
Translate the UI into Russian

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#195]
With the current set up, it is easy-peasy to translate the UI into Russian. It is all about creating a new file in the website/translations folder following the same logic as the [translations/messages.es.yaml](https://github.com/chesslablab/website/blob/main/translations/messages.es.yaml) file which serves as an example to solve this issue.

**Comment by zanzydnd** [comment]
@programarivm can help you to translate the UI into russian

**Comment by programarivm** [comment]
Excellent, thanks!

These are the i18n folders:

- [website/translations](https://github.com/chesslablab/website/tree/main/translations)
- [website/assets/js/translations](https://github.com/chesslablab/website/tree/main/assets/js/translations)

**Comment by zanzydnd** [comment]
https://github.com/chesslablab/website/pull/246
link it to issue pls
=-)
