### ISSUE TITLE
Translate the UI into French

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#199]
With the current set up, it is easy-peasy to translate the UI into French. It is all about creating a new file in the website/translations folder following the same logic as the [translations/messages.es.yaml](https://github.com/chesslablab/website/blob/main/translations/messages.es.yaml) file which serves as an example to solve this issue.

**Comment by lorlor31** [comment]
Sorry I just realized it was already done but here is my yaml translation in case you want to compare :) 
# Main nav bar
Play: Jouer 
Online: En ligne
Computer: Ordinateur
Learn: Apprendre
Classical Chess: Echecs classiques
Fischer Random: Aléatoire deFischer
FEN String: Position FEN
SAN Movetext: Mouvement (SAN)
RAV Movetext: Mouvement (RAV)
Annotated Games: Jeux commentés
Openings: OUvertures
ECO Code: Code ECO
Name: Nom
Training: Entrainement
Checkmate: Echec et mat
Database: Base de données
Search Games: Rechercher des jeux
Top Openings: Principales ouvertures
Player Stats: Statistiques du joueur
Event Stats: Statistiques des évènements
Language: Langue
Settings: Paramètres

# Play
Online Players: Joueurs en ligne
Create a Game: Créer un jeu
Play a Friend: Jouer avec un(e) ami(e)
Classical chess: Jeu classique
Enter Invite Code: Entrer un code d'invitation
Play Online: Jouer en ligne
Click an item in the list of games: Cliquer un item dans la liste de jeux
Minutes per side: Minutes par côté
Increment in seconds: Increment en secondes
Select a variant: Sélectionner une variante
Classical: Classique
Create Game: Créer un jeu
Enter a FEN: Entrer un FEN
Create Invite Code: Créer un code d'invitation
Share this code with a friend: Partager ce code avec un(e) ami(e)
Copy and Play: Copier et jouer
Invite code: Code d'invitation
Play Computer: Jouer contre l'ordinateur
Difficulty level: Niveau de difficulté
Would you like a draw?: Voulez-vous un graphique
Would you like a rematch?: Voulez-vous rejouer ?
Would you like a takeback?: Voulez-vous rejouer le dernier mouvement ?
Accept: Accepter
Decline: Refuser

# Learn
Load: Charger
Variations and comments will be removed. To keep them, load a RAV Movetext instead: Les variations et les commmentaires vont être effacés. Pour les conserver, charger un texte RAV avec les mouvements.
Enter a movetext: Entrer texte avec les mouvements
Variations and comments will be kept. To remove them, load a SAN Movetext instead: Les variations et les commmentaires vont être gardés. Pour les effacer, charger un texte SAN avec les mouvements à la place.

# Openings
Select an ECO code: Sélectionner un code ECO
Flank Openings: Ouvertures de flanc
Semi-Open Games other than the French Defense: Jeux semi-ouverts autres que la défense française
Open Games and the French Defense: Jeux ouverts et la défense française
Closed Games and Semi-Closed Games: Jeux fermés et jeux semi-ouverts
Indian Defenses: Défense indienne
Movetext: Texte avec mouvements
Search: Recherche

# Training
Select a checkmate: Sélectionner un échec et mat
Random: Aléatoire
King and queen and rook vs. king and rook: Roi et reine et tour vs. roi et tour
King and queen vs. king: Roi et reine vs. roi
King and rook vs. king: Roi et tour vs. roi
King and two bishops vs. king: Roi et deux fous vs.roi
King and bishop and knight vs. king: Roi et un fou et un cavalier vs.roi

# Database
Loading: Chargment en cours
Click on the Search button, and find up to 25 random games matching the search criteria: Cliquez sur le bouton Recherche et trouvez jusqu'à 25 jeux correspondants à vos critères de recherche !
Event: Evènement
Year: Année
White: Blancs
Black: Noirs
Result: Résultats
Click on an ECO code, and find a random game matching the search criteria: Cliquer un code ECO et trouvez un jeu correspondant à vos critères de recherche !

# Partial templates
Board: Plateau
Flip Board: Plateau tournant
Copy Movetext: Copier le texte du mouvement
Copy FEN: Copier le code FEN
Game: Jeu
Takeback: Corriger un mouvement
Propose a takeback: Proposer la correction d'un mouvement
Offer draw: Tirage au sort
Resign: Abandonner
Offer Rematch: Ofrecer revancha
Study: Etudier
Download Image: Télécharger une image
Download Video: Télécharger une video
Heuristic Charts: Graphiques heuristiques
Explain Position: Expliquer la position
Soon available! Please be patient: Bientôt disponible ! Soyez patients !
Save Changes: Sauver les changements

**Comment by programarivm** [comment]
@lorlor31 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

Happy learning!
