### ISSUE TITLE
Modal popup design for Training > Checkmate Skills

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#20]
A modal popup needs to open by clicking on **Training > Checkmate Skills** similar to the SPA version.

![figure_01](https://github.com/chesslablab/mpablab/assets/4062000/811845ba-9abc-41da-951e-c5ef8f4b24fe)
**Figure 1**. Click on **Training > Checkmate Skills**.

![figure_02](https://github.com/chesslablab/mpablab/assets/4062000/7808ba1a-c97e-4519-8302-2d085c5f798d)
**Figure 2**. Click on the **Checkmate** field.

This modal is to be implemented using [Bootstrap's JavaScript modal](https://getbootstrap.com/docs/5.0/components/modal/) plugin. No additional programming is required to close this issue — just display the modal popup, it's a really good first issue to get familiar with the codebase!

Keep it up, and happy coding.

**Comment by varshareddyarrabelli** [comment]
Hi, I am interested in working on this issue. Seems like the setup is not proper. Could someone help me with that?

**Comment by programarivm** [comment]
@varshareddyarrabelli welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

Happy learning!

**Comment by varshareddyarrabelli** [comment]
After following the installation steps, I am not able to run the application locally, 
Docker containers are not running properly.
![image](https://github.com/chesslablab/website/assets/95460134/453372f8-16da-4229-946f-9fc63684db87)

**Comment by programarivm** [comment]
The container logs will probably reveal helpful information about the problem as described at [View container logs](https://docs.docker.com/config/containers/logging/).

```
docker logs chess_website_nginx
docker logs chess_website_php_fpm
```

**Comment by varshareddyarrabelli** [comment]
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/03/28 17:35:50 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/fullchain.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)


These are the logs generated by `docker logs chess_website_nginx`

**Comment by programarivm** [comment]
As per the docs at [Run the MPA on a Docker Container](https://github.com/chesslablab/website?tab=readme-ov-file#run-the-mpa-on-a-docker-container):

> First things first, make sure to have created the `fullchain.pem` and `privkey.pem` files into the docker/nginx/ssl folder.

The same thing goes for both the PHP Chess API and the PHP Chess Server. See https://github.com/chesslablab/spablab/issues/533#issuecomment-1933635386

The certificates have been created using [Cerbot](https://certbot.eff.org/).

Finally let me suggest to enclose the command-line output in three backticks (```) for better readability.

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/03/28 17:35:50 [emerg] 1#1: cannot load certificate "/etc/nginx/ssl/fullchain.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
```

I hope this helps. Happy coding!

**Comment by varshareddyarrabelli** [comment]
Hey, I have created the `fullchain.pem` and `privkey.pem` files, but the files are empty. How to generate those certificates.

**Comment by programarivm** [comment]
The files should not be empty. The SSL certificate is necessary to keep the containers up and running on the development environment for these domain names:

- `chesslablab.org`
- `www.chesslablab.org`
- `api.chesslablab.org`
- `async.chesslablab.org`

What are the logs reporting on this occasion?

**Comment by varshareddyarrabelli** [comment]
```
varsha@DESKTOP-ODVRTM1:~/website$ docker logs chess_website_php_fpm
[31-Mar-2024 12:22:31] NOTICE: fpm is running, pid 1
[31-Mar-2024 12:22:31] NOTICE: ready to handle connections
```

`chess_website_nginx`
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/03/31 12:23:07 [emerg] 1#1: cannot load certificate "/../ssl/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/../ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/../ssl/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/../ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```

These are the docker logs

**Comment by programarivm** [comment]
The log messages seem to be quite detailed in that the SSL certificate is not set up properly.

See https://github.com/chesslablab/spablab/issues/704#issuecomment-1908583235

**Comment by varshareddyarrabelli** [comment]
This command `sudo certbot certonly --standalone` give this 

```
  Domain: chesslablab.net
  Type:   dns
  Detail: DNS problem: NXDOMAIN looking up A for chesslablab.net - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for chesslablab.net - check that a DNS record exists for this domain
```

**Comment by programarivm** [comment]
Well, more specifically, I was able to create the SSL certificate using DNS validation on an Ubuntu AWS instance. By the way, some Certbot documentation recommends to have a working web site that can already be accessed using HTTP on port 80.

See:

- [certbot instructions](https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal)
- [How To Acquire a Let's Encrypt Certificate Using DNS Validation with acme-dns-certbot on Ubuntu 18.04](https://www.digitalocean.com/community/tutorials/how-to-acquire-a-let-s-encrypt-certificate-using-dns-validation-with-acme-dns-certbot-on-ubuntu-18-04)

If this is somehow too overwhelming, alternatively a self-signed SSL certificate can be created for development purposes using [OpenSSL](https://www.openssl.org/).

```
openssl genrsa -des3 -passout pass:foobar -out acme.com.pem 2048
openssl req -passin pass:foobar -new -sha256 -key acme.com.pem -subj "/C=US/ST=CA/O=acme, Inc./CN=acme.com" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:acme.com,DNS:www.acme.com")) -out acme.com.csr
openssl x509 -passin pass:foobar -req -days 365 -in acme.com.csr -signkey acme.com.pem -out acme.com.crt
openssl rsa -passin pass:foobar -in acme.com.pem -out acme.com.key
```
The example commands above will create these files:

- `acme.com.crt`
- `acme.com.csr`
- `acme.com.key`
- `acme.com.pem`

I hope this helps, and keep it up!
