### ISSUE TITLE
Translate the UI into German

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#201]
With the current set up, it is easy-peasy to translate the UI into German. It is all about adding two files in the following folders as per the current convention.

- [website/translations](https://github.com/chesslablab/website/tree/main/translations)
- [assets/js/translations](https://github.com/chesslablab/website/tree/main/assets/js/translations)

**Comment by umigam3** [comment]
Hi there, happy learning and coding!

**Comment by programarivm** [comment]
@umigam3 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

Happy learning!
