### ISSUE TITLE
Translate the UI into Hindi

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#202]
With the current set up, it is easy-peasy to translate the UI into Hindi. It is all about adding two files in the following folders as per the current convention.

- [website/translations](https://github.com/chesslablab/website/tree/main/translations)
- [assets/js/translations](https://github.com/chesslablab/website/tree/main/assets/js/translations)

**Comment by Shubhdeep02** [comment]
hey @programarivm can i take this token?

**Comment by programarivm** [comment]
@Shubhdeep02 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

I can't wait to see what you come up with!

**Comment by Shubhdeep02** [comment]
Thanks @programarivm i have started working on the token. It's really awesome to be part of this amazing community.

**Comment by Shubhdeep02** [comment]
Raise a PR in #311 please review it.
