### ISSUE TITLE
Display annotated games in FAN notation

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#224]
![figure_01](https://github.com/chesslablab/website/assets/4062000/245f3291-d323-4f5e-9707-6e295a6ef823)
**Figure 1**. Click on **Settings** and select **Figure Algebraic Notation (FAN)**

![figure_02](https://github.com/chesslablab/website/assets/4062000/45ea6812-1fba-4191-92e4-c17b09799416)
**Figure 2**. Click on **Learn > Annotated Games** and select a game

**Comment by Shubhdeep02** [comment]
Hey @programarivm I would like to work on the issue could you elaborate more on the issue?

**Comment by programarivm** [comment]
Thank you @Shubhdeep02 for asking this question!

The annotated games are always being displayed in SAN format, however, if the notation is set to FAN they should be displayed in FAN format.

> An alternative to SAN is FAN (Figurine Algebraic Notation). FAN uses miniature piece icons instead of single letter piece abbreviations. The two notations are otherwise identical.

Standard: Portable Game Notation Specification and Implementation Guide
http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.2.3

**Comment by Shubhdeep02** [comment]
Sorry for the delay @programarivm... actually was little busy in my placement season ,targeting some good companies... can you provide some insights how to showcase myself to land a job in decent company

**Comment by programarivm** [comment]
Thank you @Shubhdeep02 for asking this question, you may want to [open a discussion](https://github.com/orgs/chesslablab/discussions) about this topic.

Keep it up,
