### ISSUE TITLE
Allow users to set up the piece set

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#228]
![screencapture-chesslablab-org-en-settings-2024-04-24-13_10_36](https://github.com/chesslablab/website/assets/4062000/38a0879b-f3f7-464e-9ef0-7e935c38a83f)
**Figure 1**. Click on **Settings**

Users should set up how they want to display the piece set: Either as Classical or as Staunty. The chess board is currently initialized in [assets/js/pages/chessboard.js](https://github.com/chesslablab/website/blob/main/assets/js/pages/chessboard.js) with the Staunty piece set by default.  

See:

- [Example: Different styles and piece sets](https://shaack.com/projekte/cm-chessboard/examples/different-styles.html)

**Comment by HatemSelim94** [comment]
Hi @programarivm, I would like to work on this issue. Thanks.

**Comment by programarivm** [comment]
@HatemSelim94, welcome to ChesslabLab.

Thank you for joining the community.

Please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

Happy coding and learning!

**Comment by programarivm** [comment]
👋 Hey @HatemSelim94, how are things going? Could you set up the website on your localhost?
