### ISSUE TITLE
Upgrade question

### ISSUE THREAD

**Issue by d47081** [chesslablab/website#229]
Hello, I have just updated server and website to latest versions with (`git pull` and `composer update`)

Now I have 404 error at the main page, and must enter `en` prefix in URI manually

Also, my route looks like this after all:
http://chesslablab.ygg/chesslablab/en/

how to make website working at the domain root as before?

upd. I think that's my nginx config just deprecated, found some info here
https://github.com/chesslablab/website/commit/b3d16ae8aea32a96f992c5cb6bcdd9061399cf5f

**Comment by programarivm** [comment]
The website is set up with the config file at [docker/nginx/conf.d/prod.conf](https://github.com/chesslablab/website/blob/main/docker/nginx/conf.d/prod.conf) with the Symfony routes defined in [config/routes.yaml](https://github.com/chesslablab/website/blob/main/config/routes.yaml).  Also remember to `composer update`.

**Comment by programarivm** [comment]
This is the redirection https://github.com/chesslablab/website/blob/main/docker/nginx/conf.d/prod.conf#L14C2-L14C55

**Comment by programarivm** [comment]
The site's cache should probably be cleared as well for [these settings](https://github.com/chesslablab/website/blob/main/assets/js/pages/apply_settings.js) to take effect if that makes sense.

**Comment by programarivm** [comment]
The URLs of the website are assumed to be as described in the following examples:

- https://chesslablab.org/en/
- https://chesslablab.org/en/learn/classical
- https://chesslablab.org/en/openings/eco-code

How does your URL looks like?
