### ISSUE TITLE
e2e tests for website

### ISSUE THREAD

**Issue by miroslavmyrha** [chesslablab/website#239]
@programarivm  

Hi, I am a developer who specializes in automation e2e testing. 
This seems like a nice project.
I could write some for the website if it would be beneficial for you.

**Comment by programarivm** [comment]
Thank you @miroslavmyrha for joining the ChesslaBlab community and for opening this issue.

Let's elaborate on end-to-end testing. What about using Selenium IDE? I was wondering if [these tests](https://github.com/chesslablab/spablab/tree/main/src/__tests__) in the SPA could be used in the ChesslaBlab website. 

Happy coding!

**Comment by miroslavmyrha** [comment]
How about Playwright or Cypress? I have decent knowledge of Cypress, but I could give it a try in Playwright. It would at least be a challenge :)

Of course, I can use selectors and scenarios from existing tests in Selenium and further develop them.
