### ISSUE TITLE
Translate the UI into Turkish

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#249]
With the current set up, it is easy-peasy to translate the UI into Turkish. It is all about adding two files in the following folders as per the current convention.

- [website/translations](https://github.com/chesslablab/website/tree/main/translations)
- [assets/js/translations](https://github.com/chesslablab/website/tree/main/assets/js/translations)

**Comment by asandikci** [comment]
@programarivm Can I use `'` character in yaml file ?

**Comment by asandikci** [comment]
@programarivm Can I add Translator Note as startin with `#` symbol in end of the file ?

**Comment by asandikci** [comment]
#264 Ready for review!

**Comment by programarivm** [comment]
> @programarivm Can I use `'` character in yaml file ?

Sure you can as per the docs at [Translations](https://symfony.com/doc/current/translation.html).
