### ISSUE TITLE
Add translation text: Draw by stalemate

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#299]
An informative message is now displayed on draw by stalemate: "Draw by stalemate."  This text needs to be translated accordingly in the translations folder:

- assets/js/translations

Happy learning!

**Comment by KartikWatts** [comment]
Hi there, happy learning and coding!
@programarivm Went through the doc. Would love to start contributing to the repo by working on this documentation enhancement. Regards.

I looked into the `translations` folder, and one point I did want to talk about is, at present for all languages, we have an object where the key is the hard-coded English string from which the string is translated to a specific language, but I was wondering what would happen if we would require to change the English string itself.
Can we use an enum or object instead to provide the English language string keys, Would love to know your thoughts.

**Comment by programarivm** [comment]
Thank you @KartikWatts for asking this question! 

It is assumed that the default language is English as per the docs at [Translations](https://symfony.com/doc/current/translation.html).

Keep it up,
