### ISSUE TITLE
Translate the UI into Hindi

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#313]
With the current set up, it is easy-peasy to translate the UI into Hindi. It is all about creating a new file in the assets/js/translations folder following the same logic as the [assets/js/translations/messages.es.js](https://github.com/chesslablab/website/blob/main/assets/js/translations/messages.es.js) file which serves as an example to solve this issue.

**Comment by Shubhdeep02** [comment]
I will handle it..

**Comment by Shubhdeep02** [comment]
please review the PR @programarivm
