### ISSUE TITLE
Simplify the JavaScript code in lines 5-19

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#314]
Can you find a way to shorten the code in lines 5-19 in the [assets/js/pages/settings/SettingsForm.js](https://github.com/chesslablab/website/blob/main/assets/js/pages/settings/SettingsForm.js) file?

```js
    // ...

    if (localStorage.getItem('locale') === 'es') {
      this.el.querySelector('select[name="locale"]').value = 'es';
    } else if (localStorage.getItem('locale') === 'fr') {
      this.el.querySelector('select[name="locale"]').value = 'fr';
    } else if (localStorage.getItem('locale') === 'ru') {
      this.el.querySelector('select[name="locale"]').value = 'ru';
    } else if (localStorage.getItem('locale') === 'tr') {
      this.el.querySelector('select[name="locale"]').value = 'tr';
    } else if (localStorage.getItem('locale') === 'de') {
      this.el.querySelector('select[name="locale"]').value = 'de';
    } else if (localStorage.getItem('locale') === 'hi') {
      this.el.querySelector('select[name="locale"]').value = 'hi';
    } else {
      this.el.querySelector('select[name="locale"]').value = 'en';
    }
    
    // ...
```

At the moment this statement consists of 15 lines of code, however, it can be written with 5 lines.

Happy coding!

**Comment by chihab1991** [comment]
Hi after a little bit of research i found that you can simplify this code by using an object.
![image](https://github.com/chesslablab/website/assets/32655186/2efd695e-efe6-453c-93f0-3625a66b60a0)

**Comment by programarivm** [comment]
@chihab1991 welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the [Contributing Guidelines](https://github.com/chesslablab/website/blob/main/CONTRIBUTING.md).

Happy learning!

**Comment by chihab1991** [comment]
thanks . I can try for a solution.
please be kind to assing me to this issue.

**Comment by retrouser955** [comment]
Correct me if I am wrong but I believe you can just
```js
this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale') ?? "en"
```

**Comment by chihab1991** [comment]
> Correct me if I am wrong but I believe you can just
> 
> ```js
> this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale') || "en"
> ```

i think this solution is more simple and efficient.

**Comment by PythonShinobi** [comment]
const locale = localStorage.getItem('locale');
switch (locale) {
  case 'es':
  case 'fr':
  case 'ru':
  case 'tr':
  case 'de':
  case 'hi':
    this.el.querySelector('select[name="locale"]').value = locale;
    break;
  default:
    this.el.querySelector('select[name="locale"]').value = 'en';
}

**Comment by PythonShinobi** [comment]
```javascript
const locale = localStorage.getItem('locale');
switch (locale) {
  case 'es':
  case 'fr':
  case 'ru':
  case 'tr':
  case 'de':
  case 'hi':
    this.el.querySelector('select[name="locale"]').value = locale;
    break;
  default:
    this.el.querySelector('select[name="locale"]').value = 'en';
}

**Comment by programarivm** [comment]
@PythonShinobi that is 13 lines of code rather than 5.

**Comment by PythonShinobi** [comment]
> @PythonShinobi that is 13 lines of code rather than 5.

Ok I will try again

**Comment by chihab1991** [comment]
i think we could do this
` if (localStorage.getItem('locale')) {
      this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale');
}else {
      this.el.querySelector('select[name="locale"]').value = "en"
}`
or simplify it more by using ternary operator
`
localStorage.getItem('locale') ? 
       this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale') : this.el.querySelector('select[name="locale"]').value = "en"
`

**Comment by programarivm** [comment]
@retrouser955, @chihab1991 and @PythonShinobi,

After some testing on my local branch, the solution needs to be as described next.

```js
    // ...

    if (localStorage.getItem('locale') !== 'en') {
      this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale');
    } else {
      this.el.querySelector('select[name="locale"]').value = 'en';
    }

    // ...
```

Otherwise the language select option won't be set properly.

![Screenshot 2024-07-02 18:00:31](https://github.com/chesslablab/website/assets/4062000/2bf74dd1-9d41-4937-9696-68204bc97380)

BTW, I just realized that the words Light and Dark need to be translated into Hindi.

Happy learning!

**Comment by retrouser955** [comment]
> @retrouser955, @chihab1991 and @PythonShinobi,
> 
> After some testing on my local branch, the solution needs to be as described next.
> 
> ```js
>     // ...
> 
>     if (localStorage.getItem('locale') !== 'en') {
>       this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale');
>     } else {
>       this.el.querySelector('select[name="locale"]').value = 'en';
>     }
> 
>     // ...
> ```
> 
> Otherwise the language select option won't be set properly.
> 
> ![Screenshot 2024-07-02 18:00:31](https://private-user-images.githubusercontent.com/4062000/345111448-2bf74dd1-9d41-4937-9696-68204bc97380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzgyNjAsIm5iZiI6MTcxOTk3Nzk2MCwicGF0aCI6Ii80MDYyMDAwLzM0NTExMTQ0OC0yYmY3NGRkMS05ZDQxLTQ5MzctOTY5Ni02ODIwNGJjOTczODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDNUMDMzOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2NkMjMyMmQwMTQ3ZjRmODFmZmYwN2NiZWM0ZjRiNmRiNzU1NmNjZWJlZTA2YzMxOGY0YzlmYTNjNmNiMDM1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-1bA2zFx5yD_v19je345pBy6brUVd62QzzypGlUB67g)
> 
> BTW, I just realized that the words Light and Dark need to be translated into Hindi.
> 
> Happy learning!

Hey! May suggest something. For whatever reason, if the local storage was corrupt the language was set to something that isn't valid, this code will fail. I suggest using the <Array>.includes() method instead of this

```js
[...validLanguages].includes(localStorage.getItem('locale')) ? this.el.querySelector('select[name="locale"]').value = localStorage.getItem('locale'); : this.el.querySelector('select[name="locale"]').value = "en"
```
