### ISSUE TITLE
Add translation texts: Light and Dark

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#316]
The translation texts describing the theme (Light and Dark) are to be translated in all files in the [translations](https://github.com/chesslablab/website/tree/main/translations) folder.

![Screenshot 2024-07-02 18:00:31](https://github.com/chesslablab/website/assets/4062000/a689072f-d1c7-42e8-8442-e05def717b9f)

**Figure 1**. Click on **Settings**

**Comment by Shubhdeep02** [comment]
@programarivm will extra text be added in the setting section accordingly in each files?

**Comment by programarivm** [comment]
Exactly, more specifically those two words are to be added in the `# Settings` section in all files.

**Comment by Shubhdeep02** [comment]
I can do in `hindi` translation one

**Comment by Shubhdeep02** [comment]
@programarivm please review it
