### ISSUE TITLE
Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#330]
![Screenshot from 2024-07-09 10-55-58](https://github.com/chesslablab/website/assets/4062000/785a15d6-454f-463b-93d7-8689466f3594)
**Figure 1**. Click on **Learn > RAV Movetext**

Uncaught SyntaxError: Unexpected reserved word at [assets/js/pages/learn/rav_movetext/ravMovetextModal.js](https://github.com/chesslablab/website/blob/main/assets/js/pages/learn/rav_movetext/ravMovetextModal.js)

**Comment by retrouser955** [comment]
https://github.com/chesslablab/website/blob/main/assets/js/pages/learn/rav_movetext/ravMovetextModal.js#L20

```diff
- this.props.form.addEventListener('submit', event => {
+ this.props.form.addEventListener('submit', async event => {
```

**Comment by programarivm** [comment]
Thank you @retrouser955 for contributing to this repo! Would you want to send a PR with the fix?

**Comment by retrouser955** [comment]
Sent one. #331
