### ISSUE TITLE
Display an informative message

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#466]
![Screenshot 2024-09-20 11:04:37](https://github.com/user-attachments/assets/8cc4bee6-0b8e-4bc8-8409-f5eb0484dd3b)
**Figure 1**. Click on **Play a Friend**. Then select **Classical chess** and type `foobar` in the **FEN** field.

```text
/start "{\"variant\":\"classical\",\"mode\":\"play\",\"settings\":{\"min\":\"5\",\"increment\":\"3\",\"color\":\"w\",\"submode\":\"friend\",\"fen\":\"foobar\",\"username\":null,\"elo\":null}}"
```

```text
{"\/start":{"message":"This game could not be created."}}
```

An info message is to be displayed informing that this game can't be started.

Keep it up,

**Comment by raghav3615** [comment]
@programarivm I have opened a pull request for this issue. Please review it

**Comment by programarivm** [comment]
Thank you @raghav3615 for contributing to this repo.

Since the FEN validation logic is already implemented in the chess server the PR has been modified accordingly.

Happy learning and coding!
