### ISSUE TITLE
Largest Contentful Paint

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#473]
The Largest Contentful Paint duration of this webpage is 3.48 seconds. To provide a good user experience, it is recommended to have a Largest Contentful Paint of 2.5 seconds or less.

**Comment by azuresphere7** [comment]
Where do we get 3.48s results? I see every contents are loaded within 2s on Lighthouse devtool

**Comment by programarivm** [comment]
![largest_contentful_paint_test](https://github.com/user-attachments/assets/631e1d48-ea15-491c-809c-0b782117a808)

Good news! This one has already been fixed. According to SEO Site Checkup the Largest Contentful Paint duration is now 2.36 seconds.
