### ISSUE TITLE
Scrollable HTML table in the Database tab

### ISSUE THREAD

**Issue by programarivm** [chesslablab/website#516]
![screencapture-chesslablab-org-en-games-2024-10-28-11_22_20](https://github.com/user-attachments/assets/7974c8a9-fc2e-4357-a821-fd107b96210e)
**Figure 1**. Visit the website, select the **Games** menu option on the main navigation bar and then click on the **Database** tab.

![screencapture-chesslablab-org-en-games-2024-10-28-11_25_04](https://github.com/user-attachments/assets/c8db6e63-85b0-44e4-913f-0c5e9b58f850)
**Figure 2**. Click on the **Result** select list, select **0-1** and click on the **Search** button.

25 random games matching the search criteria will be displayed in an HTML table.

See:

- [templates/pages/games/search_games_form.html.twig](https://github.com/chesslablab/website/blob/main/templates/pages/games/search_games_form.html.twig)
- [assets/js/pages/games](https://github.com/chesslablab/website/tree/main/assets/js/pages/games)

However, the HTML table in the **Database** tab needs to be scrollable for better usability.

**Comment by shinysherbina** [comment]
Hi there, happy learning and coding! Can I work on this issue?

**Comment by programarivm** [comment]
@shinysherbina welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the Contributing Guidelines.

Happy learning!

**Comment by Girma35** [comment]
this is not bug it is easy for solving don try to

**Comment by programarivm** [comment]
@Girma35  welcome to ChesslaBlab.

Thank you for joining the community, please make sure to read the Contributing Guidelines.

Happy coding!
